name: ai4beg
channels:
  - defaults
dependencies:
  - ipykernel=6.4.1
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - numpy=1.22.3
  - python=3.8.12
  - scikit-learn=0.24.2
  - pip=21.0.1
  - pip:
    - -r requirements.txt
